apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asia-southeast1-docker.pkg.dev/notely-459605/backend-repo/backend@sha256:cd4c9fb6dbad1e4b732887fbb9620950586820960d538bd3c13f75c5fde70b60
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/organica
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATA_REDIS_HOST
              value: redis-service
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: organica.jwtSecret
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: organica.jwtSecret
            - name: organica.jwtExpirationMs
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: organica.jwtExpirationMs
            - name: spring.security.oauth2.client.registration.google.client-id
              value: dummy-client-id
            - name: spring.security.oauth2.client.registration.google.client-secret
              value: dummy-client-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
