apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asia-southeast1-docker.pkg.dev/notely-459605/backend-repo/backend@sha256:8ddfaf1e1cac0bad7df4a794159fa8a73db175ab95eb173fe1842eb432d6f620
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_AUTOCONFIGURE_EXCLUDE
              value: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/organica
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATA_REDIS_HOST
              value: redis-service
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: organica.jwtSecret
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: organica.jwtSecret
            - name: organica.jwtExpirationMs
              valueFrom:
                configMapKeyRef:
                  name: jwt-config
                  key: organica.jwtExpirationMs
            - name: spring.security.oauth2.client.registration.google.client-id
              value: dummy-client-id
            - name: spring.security.oauth2.client.registration.google.client-secret
              value: dummy-client-secret
