apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  organica.jwtSecret: "mNxuCKyNqxyVP1crv3xJcXtWyp-v5HwT_LuGmrvLd8BGdE-EJ5h_qYwlTRZtpKZBtAKaJ-ZxBkpH37WI9ayk6Q-mNxuCKyNqxyVP1crv3xJcXtWyp-v5HwT_LuGmrvLd8BGdE-EJ5h_qYwlTRZtpKZBtAKaJ-ZxBkpH37WI9ayk6QmmdAAA"
