apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  selector:
    app: pgadmin
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: external
      port: 8888
      targetPort: 80
  type: LoadBalancer
