name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Server/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'Server/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check Java version
        run: java -version

      - name: Build with Maven Wrapper
        working-directory: ./Server
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: 'sapient-duality-456306-u2'
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev --quiet

      - name: Build and Push Docker image (Backend)
        uses: docker/build-push-action@v5
        with:
          context: ./Server
          file: ./Server/Dockerfile
          push: true
          tags: |
            asia-southeast2-docker.pkg.dev/sapient-duality-456306-u2/backend/backend:latest
            asia-southeast2-docker.pkg.dev/sapient-duality-456306-u2/backend/backend:${{ github.sha }}