name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Client/**'
      - '.github/workflows/frontend.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: 'notely-459605'
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

      - name: Build and Push Docker image (Frontend)
        uses: docker/build-push-action@v5
        with:
          context: ./Client
          file: ./Client/Dockerfile
          push: true
          tags: |
            asia-southeast1-docker.pkg.dev/notely-459605/frontend-repo/frontend:latest
            asia-southeast1-docker.pkg.dev/notely-459605/frontend-repo/frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
